name: Unit Tests

on: [pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: 1.22.x

    - name: Test
      uses: robherley/go-test-action@v0.4.1